package persistencias;
// Generated 29 ene 2024 20:56:30 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * ResultadosEurovision generated by hbm2java
 */
public class ResultadosEurovision implements java.io.Serializable {

	private int idResultadosEurovision;
	private Date fechaGala;
	private Integer espania;
	private Integer alemania;
	private Integer francia;
	private Integer italia;
	private Integer portugal;
	private Integer reinoUnido;
	private Integer polonia;
	private Integer paisesBajos;
	private Integer rumania;
	private Integer grecia;
	private String paisGanador;

	public ResultadosEurovision() {
	}

	public ResultadosEurovision(int idResultadosEurovision) {
		this.idResultadosEurovision = idResultadosEurovision;
	}

	public ResultadosEurovision(int idResultadosEurovision, Date fechaGala, Integer espania, Integer alemania,
			Integer francia, Integer italia, Integer portugal, Integer reinoUnido, Integer polonia, Integer paisesBajos,
			Integer rumania, Integer grecia, String paisGanador) {
		this.idResultadosEurovision = idResultadosEurovision;
		this.fechaGala = fechaGala;
		this.espania = espania;
		this.alemania = alemania;
		this.francia = francia;
		this.italia = italia;
		this.portugal = portugal;
		this.reinoUnido = reinoUnido;
		this.polonia = polonia;
		this.paisesBajos = paisesBajos;
		this.rumania = rumania;
		this.grecia = grecia;
		this.paisGanador = paisGanador;
	}

	public int getIdResultadosEurovision() {
		return this.idResultadosEurovision;
	}

	public void setIdResultadosEurovision(int idResultadosEurovision) {
		this.idResultadosEurovision = idResultadosEurovision;
	}

	public Date getFechaGala() {
		return this.fechaGala;
	}

	public void setFechaGala(Date fechaGala) {
		this.fechaGala = fechaGala;
	}

	public Integer getEspania() {
		return this.espania;
	}

	public void setEspania(Integer espania) {
		this.espania = espania;
	}

	public Integer getAlemania() {
		return this.alemania;
	}

	public void setAlemania(Integer alemania) {
		this.alemania = alemania;
	}

	public Integer getFrancia() {
		return this.francia;
	}

	public void setFrancia(Integer francia) {
		this.francia = francia;
	}

	public Integer getItalia() {
		return this.italia;
	}

	public void setItalia(Integer italia) {
		this.italia = italia;
	}

	public Integer getPortugal() {
		return this.portugal;
	}

	public void setPortugal(Integer portugal) {
		this.portugal = portugal;
	}

	public Integer getReinoUnido() {
		return this.reinoUnido;
	}

	public void setReinoUnido(Integer reinoUnido) {
		this.reinoUnido = reinoUnido;
	}

	public Integer getPolonia() {
		return this.polonia;
	}

	public void setPolonia(Integer polonia) {
		this.polonia = polonia;
	}

	public Integer getPaisesBajos() {
		return this.paisesBajos;
	}

	public void setPaisesBajos(Integer paisesBajos) {
		this.paisesBajos = paisesBajos;
	}

	public Integer getRumania() {
		return this.rumania;
	}

	public void setRumania(Integer rumania) {
		this.rumania = rumania;
	}

	public Integer getGrecia() {
		return this.grecia;
	}

	public void setGrecia(Integer grecia) {
		this.grecia = grecia;
	}

	public String getPaisGanador() {
		return this.paisGanador;
	}

	public void setPaisGanador(String paisGanador) {
		this.paisGanador = paisGanador;
	}

}
