package persistencias;
// Generated 26 ene 2024 19:16:10 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * ResultadosEurovision generated by hbm2java
 */
public class ResultadosEurovision implements java.io.Serializable {

	private int idResultadosEurovision;
	private Date fechaGala;
	private int espania;
	private int alemania;
	private int francia;
	private int italia;
	private int portugal;
	private int reinoUnido;
	private int polonia;
	private int paisesBajos;
	private int rumania;
	private int grecia;

	public ResultadosEurovision() {
	}

	public ResultadosEurovision(int idResultadosEurovision, Date fechaGala, int espania, int alemania, int francia,
			int italia, int portugal, int reinoUnido, int polonia, int paisesBajos, int rumania, int grecia) {
		this.idResultadosEurovision = idResultadosEurovision;
		this.fechaGala = fechaGala;
		this.espania = espania;
		this.alemania = alemania;
		this.francia = francia;
		this.italia = italia;
		this.portugal = portugal;
		this.reinoUnido = reinoUnido;
		this.polonia = polonia;
		this.paisesBajos = paisesBajos;
		this.rumania = rumania;
		this.grecia = grecia;
	}

	public int getIdResultadosEurovision() {
		return this.idResultadosEurovision;
	}

	public void setIdResultadosEurovision(int idResultadosEurovision) {
		this.idResultadosEurovision = idResultadosEurovision;
	}

	public Date getFechaGala() {
		return this.fechaGala;
	}

	public void setFechaGala(Date fechaGala) {
		this.fechaGala = fechaGala;
	}

	public int getEspania() {
		return this.espania;
	}

	public void setEspania(int espania) {
		this.espania = espania;
	}

	public int getAlemania() {
		return this.alemania;
	}

	public void setAlemania(int alemania) {
		this.alemania = alemania;
	}

	public int getFrancia() {
		return this.francia;
	}

	public void setFrancia(int francia) {
		this.francia = francia;
	}

	public int getItalia() {
		return this.italia;
	}

	public void setItalia(int italia) {
		this.italia = italia;
	}

	public int getPortugal() {
		return this.portugal;
	}

	public void setPortugal(int portugal) {
		this.portugal = portugal;
	}

	public int getReinoUnido() {
		return this.reinoUnido;
	}

	public void setReinoUnido(int reinoUnido) {
		this.reinoUnido = reinoUnido;
	}

	public int getPolonia() {
		return this.polonia;
	}

	public void setPolonia(int polonia) {
		this.polonia = polonia;
	}

	public int getPaisesBajos() {
		return this.paisesBajos;
	}

	public void setPaisesBajos(int paisesBajos) {
		this.paisesBajos = paisesBajos;
	}

	public int getRumania() {
		return this.rumania;
	}

	public void setRumania(int rumania) {
		this.rumania = rumania;
	}

	public int getGrecia() {
		return this.grecia;
	}

	public void setGrecia(int grecia) {
		this.grecia = grecia;
	}

}
