package persistencias;
// Generated 24 ene 2024 13:59:21 by Hibernate Tools 5.4.33.Final

/**
 * ResultadosFaseNacional generated by hbm2java
 */
public class ResultadosFaseNacional implements java.io.Serializable {

	private String pais;
	private String paisTercero;
	private String paisSegundo;
	private String paisPrimero;

	public ResultadosFaseNacional() {
	}

	public ResultadosFaseNacional(String pais, String paisTercero, String paisSegundo, String paisPrimero) {
		this.pais = pais;
		this.paisTercero = paisTercero;
		this.paisSegundo = paisSegundo;
		this.paisPrimero = paisPrimero;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getPaisTercero() {
		return this.paisTercero;
	}

	public void setPaisTercero(String paisTercero) {
		this.paisTercero = paisTercero;
	}

	public String getPaisSegundo() {
		return this.paisSegundo;
	}

	public void setPaisSegundo(String paisSegundo) {
		this.paisSegundo = paisSegundo;
	}

	public String getPaisPrimero() {
		return this.paisPrimero;
	}

	public void setPaisPrimero(String paisPrimero) {
		this.paisPrimero = paisPrimero;
	}

}
