
-- VER INSERT RESULTADOS_FASE_NACIONAL
SELECT * FROM RESULTADOS_FASE_NACIONAL;


-- VER INSERT RESULTADOS_FASE_NACIONAL
SELECT * FROM RESULTADOS_EUROVISION;
SELECT ID_RESULTADOS_EUROVISION, FECHA_GALA, (ESPANIA + ALEMANIA + FRANCIA + ITALIA + PORTUGAL + REINO_UNIDO + POLONIA + PAISES_BAJOS + RUMANIA + GRECIA) AS SUMA
FROM RESULTADOS_EUROVISION
ORDER BY ID_RESULTADOS_EUROVISION DESC
LIMIT 1;

